### ISSUE TITLE
Workaround unsafe removal with jni buffer address getter

### ISSUE THREAD

**Issue by Janmm14** [SpigotMC/BungeeCord#3827]
Could we use jni's [`env->GetDirectBufferAddress`](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html#GetDirectBufferAddress) and netty's [`ByteBuf#nioBuffer()`](https://netty.io/4.1/api/io/netty/buffer/ByteBuf.html#nioBuffer--) method's to duplicate our native code to have a java 24 compatible method in our natives which would just perform slightly worse?

As far as I inspected, the nioBuffer methods of netty currently create a new ByteBuffer object but as it uses [`ByteBuffer#duplicate`](https://docs.oracle.com/javase/8/docs/api/java/nio/ByteBuffer.html#duplicate--), the new ByteBuffer references to the same address.

Theoretically we could also try to check whether its feasible to use netty's [`ByteBuf#internalNioBuffer(int index, int length)`](https://netty.io/4.1/api/io/netty/buffer/ByteBuf.html#internalNioBuffer-int-int-) to avoid creating ByteBuffer duplicate. 

 _Originally posted by @Janmm14 in [#3825](https://github.com/SpigotMC/BungeeCord/issues/3825#issuecomment-2864048968)_

**Comment by md-5** [comment]
Isn't this really an issue for Netty!

**Comment by Janmm14** [comment]
No, netty just uses ByteBuffer as alternative direct buffer instead of unsafe.
They do not guarantee direct buffers have a memory address available.

They would definitely say the context switch to go to native just to read the memory address is too slow.

The issue happens due to:

1) JVM 24 warns about unsafe usage
2) Netty does not want that warnings appear by default, so they stop using Unsafe by default
3) As a result, direct buffers do not have memory address anymore by default on Java 24

**Comment by derklaro** [comment]
Starting with netty 4.2.2.Final they will use the new FFM api to allocate native buffers based on memory segments which should resolve this issue, see https://github.com/netty/netty/wiki/Java-24-and-sun.misc.Unsafe

**Comment by Janmm14** [comment]
@derklaro 
This does not resolve this issue, as the new ffm api does not expose memory addresses while we use jni and especially [`ByteBuf#memoryAddress`](https://netty.io/4.1/api/io/netty/buffer/ByteBuf.html#memoryAddress--).

It changes the possible solution tho.

**Comment by derklaro** [comment]
The FFM api does expose the address: https://docs.oracle.com/en/java/javase/24/docs/api/java.base/java/lang/foreign/MemorySegment.html#address(), not sure if that is implemented by netty tho. But the java 24 version seems to just create a ByteBuffer that is backed by a memory segment, so you can either peel the memory segment from the cleaner attached to the ByteBuf or access the address from the ByteBuffer using the FFM api: `MemorySegment.ofBuffer(<the direct buffer>).address()`

**Comment by Janmm14** [comment]
Ah great, i had looked a little into that memorysegment, but apparantly not enough.

However I looked at all relevant netty bytebuf memoryAddress implementations and found that it solely relies on java-Unsafe and does not forward to MemorySegment.address()

**Comment by derklaro** [comment]
4.2.3.Final was released yesterday, maybe worth giving it another shot? Also the adaptive allocator got a lot of improvements, so it might be worth re-enabling it again 🙂
